name: CI

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Mobile platform to build for'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - android
          - ios


env:
  NODE_VERSION: 16
  JAVA_VERSION: 17

jobs:
  build:
    name: Build web assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Build web assets
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: www
          path: www
  android:
    if: ${{ contains(fromJSON('["all", "android"]'), inputs.platform) }}
    name: Build Android platform
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: www
          path: www
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: ${{ env.JAVA_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Copy web assets to native platform
        run: npx ionic capacitor copy android --no-build
      - name: Update native platform
        run: npx ionic capacitor update android
      - name: Build with Gradle
        working-directory: android
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: android/app/build/outputs/apk/debug
  ios:
    if: ${{ contains(fromJSON('["all", "ios"]'), inputs.platform) }}
    name: Build iOS platform
    runs-on: macos-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: www
          path: www
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Copy web assets to native platform
        run: npx ionic capacitor copy ios --no-build
      - name: Update native platform
        run: npx ionic capacitor update ios
      - name: Build IPA
        id: ipabuild
        working-directory: ios
        run: >
          curl -s https://raw.githubusercontent.com/loial/_ipabuild/main/ipabuild.sh | bash >> "$GITHUB_OUTPUT"
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.ipabuild.outputs.TARGET_NAME }}.ipa
          path: ${{ steps.ipabuild.outputs.FILENAME }}


      # - name: Build and archive with xcodebuild
      #   working-directory: ios
      #   run: xcodebuild
      #     -workspace App/App.xcworkspace
      #     -scheme App
      #     -archivePath App/build/App.xarchive
      #     clean build archive
      #     CODE_SIGN_IDENTITY=""
      #     CODE_SIGNING_REQUIRED=NO
      #     CODE_SIGNING_ALLOWED="NO"
      #     CODE_SIGN_ENTITLEMENTS=""
